apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-files-disk
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azure-file
  resources:
    requests:
      storage: {{ .Values.filesDiskSize }}