apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentry-pg-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: {{ .Values.pgDiskSize }}