kind: Service
apiVersion: v1
metadata:
  name: service-sentry-redis
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: sentry-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379