apiVersion: v1
kind: Secret
metadata:
  name: sentry-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  sentry_secret_key: {{ .Values.secretKey }}
  sentry_mail_username: {{ .Values.mailUsername }}
  sentry_mail_password: {{ .Values.mailPassword }}